// Pays proposés dans le parcours « Démarrer un voyage » (liste de la maquette, noms français, ordre alphabétique).
// Fichier pur (aucune dépendance) : testable avec Node.

const RAW: [string, string][] = [
  ["AF", "Afghanistan"],
  ["ZA", "Afrique du Sud"],
  ["AL", "Albanie"],
  ["DZ", "Algérie"],
  ["DE", "Allemagne"],
  ["AD", "Andorre"],
  ["AO", "Angola"],
  ["AG", "Antigua-et-Barbuda"],
  ["SA", "Arabie saoudite"],
  ["AR", "Argentine"],
  ["AM", "Arménie"],
  ["AU", "Australie"],
  ["AT", "Autriche"],
  ["AZ", "Azerbaïdjan"],
  ["BS", "Bahamas"],
  ["BH", "Bahreïn"],
  ["BD", "Bangladesh"],
  ["BB", "Barbade"],
  ["BE", "Belgique"],
  ["BZ", "Belize"],
  ["BJ", "Bénin"],
  ["BT", "Bhoutan"],
  ["BY", "Biélorussie"],
  ["MM", "Birmanie"],
  ["BO", "Bolivie"],
  ["BA", "Bosnie-Herzégovine"],
  ["BW", "Botswana"],
  ["BR", "Brésil"],
  ["BN", "Brunei"],
  ["BG", "Bulgarie"],
  ["BF", "Burkina Faso"],
  ["BI", "Burundi"],
  ["KH", "Cambodge"],
  ["CM", "Cameroun"],
  ["CA", "Canada"],
  ["CV", "Cap-Vert"],
  ["CL", "Chili"],
  ["CN", "Chine"],
  ["CY", "Chypre"],
  ["CO", "Colombie"],
  ["KM", "Comores"],
  ["CG", "Congo"],
  ["CD", "Congo (RDC)"],
  ["KR", "Corée du Sud"],
  ["CR", "Costa Rica"],
  ["CI", "Côte d'Ivoire"],
  ["HR", "Croatie"],
  ["CU", "Cuba"],
  ["DK", "Danemark"],
  ["DJ", "Djibouti"],
  ["DM", "Dominique"],
  ["EG", "Égypte"],
  ["AE", "Émirats arabes unis"],
  ["EC", "Équateur"],
  ["ES", "Espagne"],
  ["EE", "Estonie"],
  ["SZ", "Eswatini"],
  ["US", "États-Unis"],
  ["ET", "Éthiopie"],
  ["FJ", "Fidji"],
  ["FI", "Finlande"],
  ["FR", "France"],
  ["GA", "Gabon"],
  ["GM", "Gambie"],
  ["GE", "Géorgie"],
  ["GH", "Ghana"],
  ["GR", "Grèce"],
  ["GD", "Grenade"],
  ["GP", "Guadeloupe"],
  ["GT", "Guatemala"],
  ["GN", "Guinée"],
  ["GQ", "Guinée équatoriale"],
  ["GW", "Guinée-Bissau"],
  ["GY", "Guyana"],
  ["HT", "Haïti"],
  ["HN", "Honduras"],
  ["HU", "Hongrie"],
  ["IN", "Inde"],
  ["ID", "Indonésie"],
  ["IQ", "Irak"],
  ["IR", "Iran"],
  ["IE", "Irlande"],
  ["IS", "Islande"],
  ["IL", "Israël"],
  ["IT", "Italie"],
  ["JM", "Jamaïque"],
  ["JP", "Japon"],
  ["JO", "Jordanie"],
  ["KZ", "Kazakhstan"],
  ["KE", "Kenya"],
  ["KG", "Kirghizistan"],
  ["KI", "Kiribati"],
  ["KW", "Koweït"],
  ["RE", "La Réunion"],
  ["LA", "Laos"],
  ["LS", "Lesotho"],
  ["LV", "Lettonie"],
  ["LB", "Liban"],
  ["LR", "Liberia"],
  ["LY", "Libye"],
  ["LI", "Liechtenstein"],
  ["LT", "Lituanie"],
  ["LU", "Luxembourg"],
  ["MK", "Macédoine du Nord"],
  ["MG", "Madagascar"],
  ["MY", "Malaisie"],
  ["MW", "Malawi"],
  ["MV", "Maldives"],
  ["ML", "Mali"],
  ["MT", "Malte"],
  ["MA", "Maroc"],
  ["MH", "Marshall"],
  ["MQ", "Martinique"],
  ["MU", "Maurice"],
  ["MR", "Mauritanie"],
  ["MX", "Mexique"],
  ["FM", "Micronésie"],
  ["MD", "Moldavie"],
  ["MC", "Monaco"],
  ["MN", "Mongolie"],
  ["ME", "Monténégro"],
  ["MZ", "Mozambique"],
  ["NA", "Namibie"],
  ["NR", "Nauru"],
  ["NP", "Népal"],
  ["NI", "Nicaragua"],
  ["NE", "Niger"],
  ["NG", "Nigeria"],
  ["NO", "Norvège"],
  ["NC", "Nouvelle-Calédonie"],
  ["NZ", "Nouvelle-Zélande"],
  ["OM", "Oman"],
  ["UG", "Ouganda"],
  ["UZ", "Ouzbékistan"],
  ["PK", "Pakistan"],
  ["PW", "Palaos"],
  ["PS", "Palestine"],
  ["PA", "Panama"],
  ["PG", "Papouasie-Nouvelle-Guinée"],
  ["PY", "Paraguay"],
  ["NL", "Pays-Bas"],
  ["PE", "Pérou"],
  ["PH", "Philippines"],
  ["PL", "Pologne"],
  ["PF", "Polynésie française"],
  ["PT", "Portugal"],
  ["QA", "Qatar"],
  ["CF", "République centrafricaine"],
  ["DO", "République dominicaine"],
  ["RO", "Roumanie"],
  ["GB", "Royaume-Uni"],
  ["RU", "Russie"],
  ["RW", "Rwanda"],
  ["KN", "Saint-Christophe-et-Niévès"],
  ["SM", "Saint-Marin"],
  ["VC", "Saint-Vincent-et-les-Grenadines"],
  ["LC", "Sainte-Lucie"],
  ["SB", "Salomon"],
  ["SV", "Salvador"],
  ["WS", "Samoa"],
  ["ST", "Sao Tomé-et-Principe"],
  ["SN", "Sénégal"],
  ["RS", "Serbie"],
  ["SC", "Seychelles"],
  ["SL", "Sierra Leone"],
  ["SG", "Singapour"],
  ["SK", "Slovaquie"],
  ["SI", "Slovénie"],
  ["SO", "Somalie"],
  ["SD", "Soudan"],
  ["SS", "Soudan du Sud"],
  ["LK", "Sri Lanka"],
  ["SE", "Suède"],
  ["CH", "Suisse"],
  ["SR", "Suriname"],
  ["SY", "Syrie"],
  ["TJ", "Tadjikistan"],
  ["TW", "Taïwan"],
  ["TZ", "Tanzanie"],
  ["TD", "Tchad"],
  ["CZ", "Tchéquie"],
  ["TH", "Thaïlande"],
  ["TL", "Timor oriental"],
  ["TG", "Togo"],
  ["TO", "Tonga"],
  ["TT", "Trinité-et-Tobago"],
  ["TN", "Tunisie"],
  ["TM", "Turkménistan"],
  ["TR", "Turquie"],
  ["TV", "Tuvalu"],
  ["UA", "Ukraine"],
  ["UY", "Uruguay"],
  ["VU", "Vanuatu"],
  ["VA", "Vatican"],
  ["VE", "Venezuela"],
  ["VN", "Vietnam"],
  ["YE", "Yémen"],
  ["ZM", "Zambie"],
  ["ZW", "Zimbabwe"],
];

export interface Country { code: string; name: string }

export const COUNTRIES: Country[] = RAW.map(([code, name]) => ({ code, name })).sort((a, b) => a.name.localeCompare(b.name, "fr"));

export const COUNTRY_NAME: Record<string, string> = Object.fromEntries(COUNTRIES.map((c) => [c.code, c.name]));

/** Les pays populaires de la maquette, avec leurs villes phares (texte d'aide sous le nom). */
export const POPULAR: { code: string; highlights: string }[] = [
  { code: "JP", highlights: "Tokyo, Kyoto, Osaka" },
  { code: "IT", highlights: "Rome, Florence, Venise" },
  { code: "PT", highlights: "Lisbonne, Porto, Sintra" },
  { code: "ES", highlights: "Barcelone, Madrid, Séville" },
  { code: "GR", highlights: "Athènes, Santorin, Naxos" },
  { code: "MA", highlights: "Marrakech, Fès, Essaouira" },
  { code: "TH", highlights: "Bangkok, Chiang Mai, Phuket" },
  { code: "US", highlights: "New York, San Francisco, Los Angeles" },
  { code: "GB", highlights: "Londres, Édimbourg, Liverpool" },
  { code: "HR", highlights: "Split, Dubrovnik, Zagreb" },
  { code: "IS", highlights: "Reykjavik, Vík, Akureyri" },
  { code: "MX", highlights: "Mexico, Oaxaca, Tulum" },
  { code: "ID", highlights: "Ubud (Bali), Yogyakarta, Jakarta" },
  { code: "VN", highlights: "Hanoï, Hội An, Hô Chi Minh-Ville" },
  { code: "CA", highlights: "Montréal, Québec, Vancouver" },
  { code: "NO", highlights: "Oslo, Bergen, Tromsø" },
];

/** Drapeau en emoji à partir du code pays (natif sur Android et iOS ; deux lettres sur Windows). */
export function flagEmoji(code: string): string {
  return String.fromCodePoint(...[...code.toUpperCase()].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65));
}

const plain = (s: string): string => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();

/** Recherche sans accents ni casse dans le nom français. */
export function searchCountries(query: string): Country[] {
  const q = plain(query.trim());
  return q ? COUNTRIES.filter((c) => plain(c.name).includes(q)) : COUNTRIES;
}
